# Site settings
title: mais um site sobre
subtitle: estatÃ­sticas e outras coisas
email: arthurlustosaa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/maisumsitesobre" # the subpath of your site, e.g. /blog/
url: "https://arthurlustosa.github.io/maisumsitesobre/" # the base hostname & protocol for your site
twitter_username: arthurlustosa_
github_username:  arthurlustosa
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
